### ISSUE TITLE
Recognize wikilinks

### ISSUE THREAD

**Issue by gemisigo** [coddingtonbear/obsidian-csv-table#5] opened 2021-11-04 15:54 UTC
It would be great if this plugin could render the contents of the csv in a way so that Obsidian could recognize (and allow clicking) the wikilinks in it. Having a wikilink in a row anywhere but the last column will not render that row at all. Having it in the last column will show it as plain text.

**Comment by coddingtonbear** [comment] 2021-11-25 23:39
This is a duplicate of #2

**Closed by coddingtonbear** 2021-11-25 23:39 UTC
Labels: enhancement, good first issue, pull request welcome
